services:
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=bankuser
      - QUARKUS_DATASOURCE_PASSWORD=bankpass
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/bankdata
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-database
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: