services:
  database:
    image: postgres:15
    container_name: postgres-database
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=bankuser
      - QUARKUS_DATASOURCE_PASSWORD=bankpass
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/bankdata
      - EXCHANGE_API_KEY=a5685c974194564c44c50ee1
      - EXCHANGE_API_URL=https://v6.exchangerate-api.com/v6/
    depends_on:
      - database
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: