services:
  database:
    image: postgres:15
    container_name: postgres-database
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_USERNAME: bankuser
      QUARKUS_DATASOURCE_PASSWORD: bankpass
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/bankdata
      EXCHANGE_API_KEY: 
      EXCHANGE_API_URL: https://v6.exchangerate-api.com/v6/
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: